### GET request to example server
GET http://localhost:8080/api/books/

### addBooks
POST localhost:8080/api/books/addbook/
Content-Type: application/json

{
  "isbn": "1234567890123",
  "mainTitle": "Spring Boot Basics",
  "genre": "Technology"
}

### Delete all records
DELETE localhost:8080/api/books/deletebooks/

### PagingAndSortingRepository  findBookByMainTitle
GET http://localhost:8080/book-resource/search/findBookByMainTitle?title=Spring&Boot%Basi

### PagingAndSortingRepository
GET localhost:8080/book-resource

### PagingAndSortingRepository get an book by id
GET localhost:8080/book-resource/2

### PagingAndSortingRepository addBook
POST localhost:8080/book-resource
Content-Type: application/json

{
  "isbn": "1234567890125",
  "mainTitle": "Spring Boot Basi",
  "genre": "Technology",
  "author": "maarten postma"
}

### Delete record by id in book Reource
DELETE http://localhost:8080/book-resource/2

###
GET localhost:8080



### Add record for genres
POST localhost:8080/api/genre/
Content-Type: application/json

{
  "genreType": "test2"
}